#!/bin/bash
#SBATCH --job-name=RN20_LTH
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-24:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o RN20_LTH.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate prune_cry


for sparsity in 0.2
do
    python main.py --sparse --seed 17 --sparse_init iterative_gm --sparse_mode fix --lr 0.1 --sparsity $sparsity \
    --model cifar_resnet_20 --data cifar10 --epoch 160 --growth gradient --death magnitude --update_frequency 1000 --imp_iters 11 --output_dir ./output/LTH/
done


