#!/bin/bash
#SBATCH --job-name=RN20_SNIP
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-24:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o RN20_SNIP.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate prune_cry


for sparsity in 0.2 0.36 0.488 0.590 0.672 0.738 0.791 0.8325 0.866 0.893
do

    python main.py --sparse --seed 17 --sparse_init snip --sparse_mode DST --lr 0.1 --sparsity $sparsity \
    --model cifar_resnet_20 --data cifar10 --epoch 160 --update_frequency 1000

done


