#!/bin/bash
#SBATCH --job-name=RN20_GMP
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-24:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o RN20_GMP.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate prune_cry


for model in cifar_resnet_20 cifar_resnet_32 cifar_resnet_44 cifar_resnet_56 cifar_resnet_110
do
    python main.py --sparse --seed 17 --sparse_init dense --sparse_mode GMP --lr 0.1 --density 0.05 --model cifar_resnet_20 --data cifar10 --epoch 160 --initial_prune_time 0.0 --update_frequency 100
done

conda deactivate torch151
